"""Logger Port — 结构化日志抽象"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Logger(Protocol):
    """日志记录器接口"""

    def bind(self, **ctx: Any) -> Logger: ...
    def debug(self, msg: str, **kw: Any) -> None: ...
    def info(self, msg: str, **kw: Any) -> None: ...
    def warning(self, msg: str, **kw: Any) -> None: ...
    def error(self, msg: str, **kw: Any) -> None: ...
    def exception(self, msg: str, **kw: Any) -> None: ...


class NullLogger:
    """空日志实现，所有方法均为 no-op"""

    def bind(self, **ctx: Any) -> NullLogger:
        return self

    def debug(self, msg: str, **kw: Any) -> None: ...
    def info(self, msg: str, **kw: Any) -> None: ...
    def warning(self, msg: str, **kw: Any) -> None: ...
    def error(self, msg: str, **kw: Any) -> None: ...
    def exception(self, msg: str, **kw: Any) -> None: ...
